In [27]:
import numpy as np    #importing numpy

Checking how efficient numpy is

In [13]:
L = range(1000)                    #checking time taken to square 1000  numbers  for loop by defining  function
def sq(x):    
    for i in x:
        a = i**2
%timeit {sq(L)}

520 µs ± 2.41 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
%timeit {i**2 for i in L}             #checking time  taken to square 1000  numbers  for loop

383 µs ± 69.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [26]:
a = np.arange(1000)           #checking timetaken to square 1000  numbers using numpy
%timeit a**2

2.03 µs ± 345 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Numpy commands

In [28]:
a = np.array([1,2,3,4,5])         #tells the dimension of array
a.ndim

1

In [30]:
a.shape                      #tells the shape(rows and columns) of array

(5,)

In [31]:
len(a)                        #tells the length of array

5

In [33]:
a =np.ones((3,3))         #ones matrix  
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
a = np.zeros((3,3))   #zero matrix
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
a = np.random.rand(4)
a                              #uniform random number


array([0.29785856, 0.73320096, 0.09158469, 0.8153707 ])

In [41]:
a = np.random.randn(4)        #normal distributed random number
a

array([ 1.5094779 , -2.25937838, -0.72154094, -0.58970572])

In [44]:
a = np.array([1,2,3,4,5])
a*45                          # we can apply methametical operation on numpya  

array([ 45,  90, 135, 180, 225])

In [45]:
a +5

array([ 6,  7,  8,  9, 10])

In [46]:
b = [2,3,4,6,7]    #It check each any every elements of an array
a==b

array([False, False, False, False, False])

In [49]:
np.array_equal(a,b)         #it check complete on array

False

In [50]:
c = [1,2,3,4,5]               
np.array_equal(a,c)

True

In [52]:
np.sin(2)      #you apply any trignometric funtion

0.9092974268256817

other reduction

In [53]:
x = np.array([1,2,3,4,5,6,10])
x.min()

1

In [54]:
x.max()

10

In [55]:
x.argmin()

0

In [56]:
x.argmax()

6

In [57]:
x.mean()

4.428571428571429